### ISSUE TITLE
Option to specify prefix

### ISSUE THREAD

**Issue by darkdragon-001** [skorokithakis/apt-btrfs-snapshot#1]
I would suggest to use an apt config variabale (e. g. `APT::Snapshots::Prefix`) to overwrite the default prefix. It should also be possible to set a path (either allow `/` in prefix or add another variable `APT::Snapshots::Location`).

This should overwrite the [default value](https://github.com/skorokithakis/apt-btrfs-snapshot/blob/95744d8e5c7300887f98dc8d54068dc04d5225fd/apt_btrfs_snapshot.py#L108).

For querying, I suggest using [python-apt](https://launchpad.net/python-apt/), specifically [`find()`](https://apt.alioth.debian.org/python-apt-doc/library/apt_pkg.html#apt_pkg.Configuration.find) or [`find_dir()`](https://apt.alioth.debian.org/python-apt-doc/library/apt_pkg.html#apt_pkg.Configuration.find_dir).

**Comment by skorokithakis** [comment]
Hmm, I'm not sure this is the right place for this, as this is a personal fork that won't go into any upstream repos.

**Comment by darkdragon-001** [comment]
Okay. I will use my fork until the maintainer answers me or I find another option to contribute upstream...
